# Generated by Django 4.2.30 on 2026-05-31 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de catégorie')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'événement")),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='events/banners/', verbose_name='Image de bannière')),
                ('location', models.CharField(max_length=255, verbose_name="Lieu de l'événement")),
                ('start_time', models.DateTimeField(verbose_name='Date de début')),
                ('end_time', models.DateTimeField(verbose_name='Date de fin')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('total_capacity', models.PositiveIntegerField(verbose_name='Capacité totale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.category', verbose_name='Catégorie')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Organisateur')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=10, verbose_name='Rangée')),
                ('number', models.PositiveIntegerField(verbose_name='Numéro de siège')),
                ('category', models.CharField(choices=[('VIP', 'Premium VIP'), ('GOLD', 'Zone Or'), ('STANDARD', 'Standard')], default='STANDARD', max_length=20, verbose_name='Catégorie de place')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('LOCKED', 'Verrouillé temporairement'), ('RESERVED', 'Réservé / Payé')], default='AVAILABLE', max_length=20, verbose_name='Statut')),
                ('locked_by_session', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de session verrouillante')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de verrouillage')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='events.event', verbose_name='Événement')),
            ],
            options={
                'verbose_name': 'Siège',
                'verbose_name_plural': 'Sièges',
                'ordering': ['row', 'number'],
                'unique_together': {('event', 'row', 'number')},
            },
        ),
    ]
