# Generated by Django 4.2.30 on 2026-05-31 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('currency', models.CharField(default='EUR', max_length=10, verbose_name='Devise')),
                ('method', models.CharField(choices=[('CARD', 'Carte bancaire'), ('PAYPAL', 'PayPal'), ('ORANGE_MONEY', 'Orange Money'), ('MTN_MOMO', 'MTN Mobile Money')], default='CARD', max_length=30, verbose_name='Moyen de paiement')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Payé'), ('FAILED', 'Échoué')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('transaction_id', models.CharField(max_length=255, unique=True, verbose_name='ID de transaction')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Numéro de téléphone')),
                ('otp_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Code OTP')),
                ('gateway_logs', models.TextField(blank=True, null=True, verbose_name='Logs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='reservations.reservation', verbose_name='Réservation')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
    ]
